# Generated by Django 4.2.2 on 2026-03-25 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="booking",
            options={"ordering": ["-date"]},
        ),
        migrations.AlterModelOptions(
            name="table",
            options={"ordering": ["name"]},
        ),
        migrations.AlterField(
            model_name="booking",
            name="date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="booking",
            name="table",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to="db.table",
            ),
        ),
        migrations.AlterField(
            model_name="table",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.UniqueConstraint(
                fields=("date", "table"), name="unique_table_date"
            ),
        ),
    ]
